spring.application.name=delivery-service
spring.config.import=optional:classpath:application-secret.properties

server.port=8085

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_delivery?useUnicode=true&serverTimezone=Asia/Seoul

spring.jpa.hibernate.ddl-auto=update
